# api-keys.yaml
apiVersion: v1
kind: Secret
metadata:
  name: user1-key
  namespace: default
  labels:
    konghq.com/credential: key-auth
  annotations:
    konghq.com/consumer: user1
type: Opaque
stringData:
  key: "my-secret-api-key-123"
---
apiVersion: v1
kind: Secret
metadata:
  name: user2-key
  namespace: default
  labels:
    konghq.com/credential: key-auth
  annotations:
    konghq.com/consumer: user2
type: Opaque
stringData:
  key: "another-secret-key-456"