# key-auth-plugin.yaml
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: key-auth
  namespace: default
plugin: key-auth
config:
  key_names:
  - "apikey"
  - "x-api-key"
  key_in_header: true
  key_in_query: true
  key_in_body: false
  hide_credentials: true