# rate-limited-key-auth.yaml
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rate-limit
  namespace: default
plugin: rate-limiting
config:
  minute: 100
  hour: 1000
  policy: local
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: rate-limited-api
  namespace: default
  annotations:
    konghq.com/plugins: key-auth,rate-limit
spec:
  parentRefs:
  - name: kong-gateway
    namespace: kong
  hostnames:
  - "api.example.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /limited
    backendRefs:
    - name: echo-service
      port: 80