{{- range .Values.services }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}-ingress
  namespace: {{ $.Release.Namespace }}
  {{- if .secure }}
  annotations:
    konghq.com/plugins: key-auth
    konghq.com/strip-path: "true"
  {{- end }}
spec:
  ingressClassName: {{ $.Values.ingressClass }}
  rules:
    - http:
        paths:
          - path: {{ .path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .name }}
                port:
                  number: {{ .port }}
{{- end }}